name: script_inliner
description: A transformer to inline script content during a build.
version: 0.0.3
author: Seth Ladd <sethladd@gmail.com>
homepage: https://github.com/sethladd/script_inliner
dependencies:
  barback: '>=0.15.0 <0.16.0'
  html5lib: ">=0.10.0 <0.11.0"
  code_transformers: ">=0.1.3 <0.2.0"
dev_dependencies:
  browser: any
transformers:
- script_inliner
